# Generated by Django 5.2.4 on 2025-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=100)),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("file_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor"], name="receipt_rec_vendor_497c47_idx"
                    ),
                    models.Index(
                        fields=["transaction_date"],
                        name="receipt_rec_transac_b74e11_idx",
                    ),
                    models.Index(
                        fields=["category"], name="receipt_rec_categor_733426_idx"
                    ),
                ],
            },
        ),
    ]
